# Generated by Django 6.0.2 on 2026-03-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='r2_key',
            new_name='s3_key',
        ),
    ]
