# Generated by Django 6.0.2 on 2026-03-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_r2_key_photo_s3_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='s3_key',
            new_name='object_key',
        ),
    ]
