# Generated by Django 6.0.2 on 2026-03-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='object_key',
        ),
        migrations.AlterField(
            model_name='selection',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='gallery.photo'),
        ),
        migrations.RemoveField(
            model_name='selection',
            name='flag',
        ),
    ]
