# Generated by Django 6.0.2 on 2026-03-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_flag_delete_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
