# Generated by Django 6.0.2 on 2026-09-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_merge_0013_alter_gallery_name_0013_zipdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='cosplayer',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_photos', to='gallery.gallery'),
        ),
        migrations.CreateModel(
            name='GalleryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gallery.gallery')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gallery.photo')),
            ],
            options={
                'db_table': 'gallery_memberships',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='galleries',
            field=models.ManyToManyField(related_name='photos', through='gallery.GalleryMembership', to='gallery.gallery'),
        ),
        migrations.AddConstraint(
            model_name='gallerymembership',
            constraint=models.UniqueConstraint(fields=('gallery', 'photo'), name='unique_gallery_photo'),
        ),
    ]
