# Generated by Django 6.0.2 on 2026-03-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_s3_key_photo_object_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='gallery.photo'),
        ),
    ]
