# Generated by Django 6.0.2 on 2026-03-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_selection_multi_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
