# Generated by Django 6.0.2 on 2026-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_selection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='object_key',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='preview_key',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_key',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
