# Generated by Django 6.0.2 on 2026-03-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_photo_object_key_photo_preview_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField(choices=[(0, 'final'), (1, 'rose'), (2, 'lavender'), (3, 'sage'), (4, 'sky'), (5, 'amber')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='gallery.photo')),
            ],
            options={
                'db_table': 'flags',
                'unique_together': {('photo', 'color')},
            },
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
