# Generated by Django 6.0.2 on 2026-03-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_photo_replace_object_key_with_nextcloud_path'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('gallery', 'filename', 'is_edited'), name='unique_photo_per_gallery'),
        ),
    ]
