# Generated by Django 6.0.2 on 2026-03-27 22:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_unique_photo_per_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(default='pending')),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('file_path', models.TextField(blank=True, default='')),
                ('file_size', models.BigIntegerField(default=0)),
                ('celery_task_id', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_downloads', to='gallery.gallery')),
            ],
            options={
                'db_table': 'zip_downloads',
            },
        ),
    ]
