# Generated by Django 6.0.2 on 2026-06-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_gallery_name'),
        ('gallery', '0013_zipdownload'),
    ]

    operations = [
    ]
