"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import environ


ENV = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '../.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Raises Django's ImproperlyConfigured
# exception if SECRET_KEY not in os.environ
SECRET_KEY = ENV('SECRET_KEY')

# False if not in os.environ because of casting above
DEBUG = ENV('DEBUG')

ALLOWED_HOSTS = ENV('ALLOWED_HOSTS').split(' ')
CSRF_TRUSTED_ORIGINS = ENV('CSRF_TRUSTED_ORIGINS').split(' ')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'gallery.apps.GalleryConfig',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if ENV.bool('USE_SQLITE', default=False):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": ENV('DB_NAME'),
            "USER": ENV('DB_USER'),
            "PASSWORD": ENV('DB_PASSWORD'),
            "HOST": ENV('DB_HOST'),
            "PORT": ENV('DB_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Object Storage Configuration
OBJECT_STORAGE_ENDPOINT_URL = ENV('OBJECT_STORAGE_ENDPOINT_URL', default='')
OBJECT_STORAGE_ACCESS_KEY_ID = ENV('OBJECT_STORAGE_ACCESS_KEY_ID', default='')
OBJECT_STORAGE_SECRET_ACCESS_KEY = ENV('OBJECT_STORAGE_SECRET_ACCESS_KEY', default='')
OBJECT_STORAGE_BUCKET_NAME = ENV('OBJECT_STORAGE_BUCKET_NAME', default='')

# Nextcloud WebDAV (for downloading originals in zip export)
NEXTCLOUD_WEBDAV_URL = ENV('NEXTCLOUD_WEBDAV_URL', default='')
NEXTCLOUD_USERNAME = ENV('NEXTCLOUD_USERNAME', default='')
NEXTCLOUD_APP_PASSWORD = ENV('NEXTCLOUD_APP_PASSWORD', default='')

# API Authentication — supports comma-separated keys for zero-downtime rotation
API_KEYS = [k.strip() for k in ENV('API_KEY').split(',') if k.strip()]

# Security — production only (TLS terminated by Cloudflare / Uberspace proxy)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000

# Celery
CELERY_BROKER_URL = ENV('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = ENV('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Zip downloads
ZIP_DOWNLOAD_DIR = BASE_DIR / 'zip_downloads'
ZIP_DOWNLOAD_MAX_AGE_SECONDS = 3600  # clean up after 1 hour

# Disable DRF browsable API in production
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
} if not DEBUG else {}